create table famille
(
    FAM_CODE INT(11) NOT NULL AUTO_INCREMENT,
    FAM_LIBELLE varchar(200),
    PRIMARY KEY (FAM_CODE)
);

create table dosage
(
    DOS_CODE INT(11) NOT NULL AUTO_INCREMENT,
    DOS_QUANTITE varchar(200),
    DOS_UNITE varchar(200),
    PRIMARY KEY (DOS_CODE)
);

create table type_individu
(
    TIN_CODE INT(11) NOT NULL AUTO_INCREMENT,
    TIN_LIBELLE varchar(200),
    PRIMARY KEY (TIN_CODE)
);

create table medicament
(
    MED_DEPOTLEGAL INT(11) NOT NULL AUTO_INCREMENT,
    MED_NOMCOMMERCIAL varchar(40),
    FAM_CODE int(11) NOT NULL,
    MED_COMPOSITION varchar(255),
    MED_EFFETS varchar(255),
    MED_CONTREINDIC varchar(255),
    MED_PRIXECHANTILLON float(50),
    PRIMARY KEY (MED_DEPOTLEGAL),
    FOREIGN KEY (FAM_CODE) REFERENCES famille(FAM_CODE)
);

create table interagis
(
    MED_PERTURBATEUR INT(11) NOT NULL,
    MED_MED_PERTURBE INT(11) NOT NULL,
		PRIMARY KEY(MED_PERTURBATEUR,MED_MED_PERTURBE),
    FOREIGN KEY (MED_PERTURBATEUR) REFERENCES medicament(MED_DEPOTLEGAL),
    FOREIGN KEY (MED_MED_PERTURBE) REFERENCES medicament(MED_DEPOTLEGAL)
);

create table prescrire
(
    MED_DEPOTLEGAL INT(11) NOT NULL, TIN_CODE INT(11) NOT NULL, 
		DOS_CODE int(11) NOT NULL, PRE_POSOLOGIE varchar(200),
		PRIMARY KEY(MED_DEPOTLEGAL,TIN_CODE,DOS_CODE),    
		FOREIGN KEY (MED_DEPOTLEGAL) REFERENCES medicament(MED_DEPOTLEGAL),
    FOREIGN KEY (TIN_CODE) REFERENCES type_individu(TIN_CODE),
    FOREIGN KEY (DOS_CODE) REFERENCES dosage(DOS_CODE) 
);